export const ROUTES = {
  signup: "/signup",
  signin: "/signin",
  forgotPassword: "/forgot-password",
  registrationSteps: "/registration-steps",
  registrationStepsAvatar: "/registration-steps/avatar",
  profile: (username: string) => `/${username}`,
  editProfile: (username: string) => `/${username}/edit`,
  editInterests: (username: string) => `/${username}/interests`,
  about: "/about",
  feed: "/feed",
  friends: "/friends",
  photos: (username: string) => `/${username}/photos`,
  favorites: "/favorites",
  places: "/places",
  notifications: "/notifications",
  messages: "/messages",
} as const;
